### ISSUE TITLE
Quantpedia 136: Residual Momentum

### ISSUE THREAD

**Issue by gurusawhney** [QuantConnect/Tutorials#132]
https://quantpedia.com/Screener/Details/136
-uses regression model which is calculated every month for all eligible stocks using the Fama and French three factors as independent variables.

**Comment by DerekMelchin** [comment]
Started on 4/24/2020.
Fama and French data gathered from https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html
