### ISSUE TITLE
Cointegration Strategy not correctly implemented

### ISSUE THREAD

**Issue by HalldorAndersen** [QuantConnect/Tutorials#201]
### Expected Behavior
Let's imagine we have two stocks, Y and X. When going long the 'spread', we invest k% of our portfolio to
buy Y while simultaneously selling (the quantity of stock in X which equals the market value of our position in Y)*Beta. The regression coefficient Beta is established by finding a linear relationship between log(Y) and log(X). 

The algorithm should put on a long 'spread' position when the value of the spread
exceeds mean(spread) - StdDev(spread) and a short 'spread' position when the value of 
spread exceeds mean(spread) + StdDev(spread).

The algorithm should close all positions when the spread crosses the mean of the spread, from either direction.

### Actual Behavior
Price ratio between stock price Y and X is being used to determine the size of the position in stock X instead of using the regression coefficient Beta. Also, the number of shares bought/sold for stock X should be a function of the market value of stock Y.

The current value of spread, spread[-1], which is being used to go long or short, returns the first element in the spread series, instead of the latest.

No mechanism is established to close all positions when the spread reverts to mean.

### Potential Solution
1. Use the regression coefficient Beta, and the market value of the position in stock Y to determine position sizing in stock X.
2. Retrieve correct current value for the spread.
3. Implement a fix to close all positions when the spread reverts to mean.

### Reproducing the Problem
Running the Cointegration trading algorithm in the QC Strategy Library will reproduce this problem. See the algorithm at the link below.

https://www.quantconnect.com/tutorials/strategy-library/pairs-trading-copula-vs-cointegration

### Checklist

- [x] I have completely filled out this template 

- [x] I have confirmed that this issue exists on the current master branch

- [x] I have confirmed that this is not a duplicate issue by searching issues 

- [x]  I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Running these algorithms in live mode, we have discovered that some class variables are not initialized and result in runtime errors such as:
```
Runtime Error: AttributeError : 'CopulaPairsTradingAlgorithm' object has no attribute 'theta'
```

**Comment by AlexCatarino** [comment]
See #196
