### ISSUE TITLE
Strategy 28: i.MarketCap creates error

### ISSUE THREAD

**Issue by xinweimetrics** [QuantConnect/Tutorials#240]
After cloning the [Strategy 28: Small Capitalization Stocks Premium Anomaly](https://github.com/QuantConnect/Tutorials/tree/master/04%20Strategy%20Library/28%20Small%20Capitalization%20Stocks%20Premium%20Anomaly) and running it, I receive 'FineFundamental' object has no attribute 'MarketCap' error.

**Potential Solution**

Replace this piece of code

```    
for i in fine:
    i.MarketCap = (i.EarningReports.BasicAverageShares.ThreeMonths * 
                      i.EarningReports.BasicEPS.TwelveMonths *
                      i.ValuationRatios.PERatio)

sorted_market_cap = sorted([x for x in fine if x.MarketCap > 0], key=lambda x: x.MarketCap)
```

with

```
market_cap = {}

# Calculate the market cap and add the "MarketCap" property to fine universe object
for i in fine:
    market_cap[i] = (i.EarningReports.BasicAverageShares.ThreeMonths *
                      i.EarningReports.BasicEPS.TwelveMonths *
                      i.ValuationRatios.PERatio)

sorted_market_cap = sorted([x for x in fine if market_cap[x] > 0], key=lambda x: market_cap[x])
```

So, both the code snippet in "02 Method.html" and the backtest URL in "03 Algorithm.html" need to be updated.

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Tutorials/pull/258
