### ISSUE TITLE
Why are these files missing?

### ISSUE THREAD

**Issue by CBrauer** [QuantConnect/Tutorials#350]
Hey,

I'm looking at Lean-Tutorials\03 Open Source\05 Brokerage Development Guide and files
for steps 05 through 11 are empty!

Charles

**Comment by jaredbroad** [comment]
Because they have not been written yet. 
https://github.com/QuantConnect/Tutorials/blob/master/03%20Open%20Source/05%20Brokerage%20Development%20Guide/00.html#L42
