### ISSUE TITLE
"You can also see out Tutorials and Videos" Typo?

### ISSUE THREAD

**Issue by powderblock** [QuantConnect/Tutorials#62]
I believe "out" should changed to "our".

I tried finding this in the code, but I was unable to find the bottom content HTML.

<img width="1280" alt="screen shot 2018-04-21 at 5 17 45 pm" src="https://user-images.githubusercontent.com/1458607/39090003-f4c6c504-4587-11e8-8b8e-f452be0c2802.png">

**Comment by gaviles** [comment]
@powderblock thank you for the report :), The typo was part of a template html file that is not part of the documentation repo. The fixed file is now in production.

Regards, Gustavo.
